image: maven:latest


variables:
    MAVEN_CLI_OPTS: "--batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
cache:
    paths:
    - .m2/target
    MAVEN_CLI_OPTS: "--batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
    paths:
    - .m2/repository/
    - target/

stages:
    - build
    - test

build:
    stage: build
    script:
    - mvn $MAVEN_CLI_OPTS compile

test1:
    stage: test
    script:
        - mvn $MAVEN_CLI_OPTS test
    artifacts:
        paths:
        - target/

test2:
    stage: test
    coverage: '/Total.*?([0-9]{1,3})%/'
    script:
        - mvn $MAVEN_CLI_OPTS test
        - cat target/site/jacoco/index.html
    artifacts:
        paths:
        - target/
